# Generated by Django 6.0 on 2025-12-12 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('importance', models.IntegerField(default=3)),
                ('urgency_flag', models.BooleanField(default=False)),
                ('estimated_hours', models.FloatField(default=1.0)),
                ('dependencies', models.IntegerField(default=0)),
                ('value_score', models.IntegerField(default=5)),
                ('recurrence', models.CharField(default='none', max_length=20)),
                ('owner_load', models.FloatField(default=0.0)),
                ('context_match', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('category', models.CharField(default='feature', max_length=50)),
                ('priority_label', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('priority_confidence', models.FloatField(blank=True, null=True)),
                ('priority_reason', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
